---
title: "app11"
author: "Emma Schwartz"
date: "11/23/2020"
output: html_document
runtime: shiny
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(shiny)

d = read_csv("data.csv")
variables_names = names(d)

ui <- fluidPage(
  
  titlePanel("Housing Prices"),
  
  sidebarLayout(
    
    sidebarPanel(
      
      checkboxGroupInput(inputId = "floors", label = "Select number of floors",
                         choices = names(table(d$floors)), inline = TRUE),

      selectInput(
        inputId ="var1",
        label = "Select a Numeric Variable",
        choices = variables_names, selected = "price"),
      
      sliderInput(inputId = "sqft_living",
                  "Select Square Foot Area Range:",
                  min = min(d$sqft_living, na.rm=TRUE),
                  max = max(d$sqft_living, na.rm=TRUE),
                  value = c(0,6000)),
      
      radioButtons(inputId = "plot_choice", 
                   label = h3("Select Plot:"),
                   choices = c("Histogram Plot" = "histogram",
                     "Boxplot" = "boxplot"),
                   selected = 'histogram')
      
    ),

    mainPanel(
      plotOutput(outputId = 'show_plot')
    )
  )
)

 
server <- function(input, output) {
  output$show_plot <- renderPlot({
    
    v1 = input$var1
   
    d <- d %>% filter(floors %in% input$floors, sqft_living >input$sqft_living[1], 
                      sqft_living<input$sqft_living[2])
    
    library(ggplot2)
    if(input$plot_choice == 'histogram')
    {
      ggplot(d, aes(x = d[[v1]]))+
        geom_histogram()+
        labs(x = v1)
    }
    
    else
    {
      ggplot(d, aes(x = d[[v1]]))+
        geom_boxplot()+
        labs(x = v1)
    }
  })
}
# app
shinyApp(ui = ui, server = server)
```


