---
title: "app6"
author: "Emma Schwartz"
date: "11/23/2020"
output: html_document
runtime: shiny
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(shiny)

d = read_csv('titanic.csv')

variables_names = names(d)

ui <- fluidPage(
  
  titlePanel("Plot Selection"),
  
  sidebarLayout(
    
    sidebarPanel(
      
      selectInput(
        inputId ="var1",
        label = "Select a Numeric Variables",
        choices = variables_names, selected = "Age"
      ),
      
      selectInput(
        inputId ="var2",
        label = "Select a Numeric Variables",
        choices = variables_names,
        selected = "Fare"
      ),
      
      radioButtons(inputId = "plot_choice", 
                   label = h3("Select Plot:"),
                   choices = c("Scatter Plot" = "point",
                     "Line Plot" = "line"),
                   selected = 'line')
      
    ),

    mainPanel(
      plotOutput(outputId = 'show_plot')
    )
  )
)

 
server <- function(input, output) {
  
  output$show_plot <- renderPlot({
    
    v1 = input$var1
    v2 = input$var2
   
    
    library(ggplot2)
    
    if(input$plot_choice == 'point')
      
    {
      ggplot(d, aes(x = d[[v1]], y = d[[v2]]))+
        geom_point()+
        labs(x = v1, y = v2)
    }
    
    else
    {
      ggplot(d, aes(x = d[[v1]], y = d[[v2]]))+
        geom_line()+
        labs(x = v1, y = v2)
    }
  })
}
# app
shinyApp(ui = ui, server = server)
```

