---
title: "app8"
author: "Emma Schwartz"
date: "11/23/2020"
output: html_document
runtime: shiny
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(shiny)

d = read_csv('titanic.csv')

variables_names = names(d)

ui <- fluidPage(
  
  titlePanel("Plot Selection"),
  
  sidebarLayout(
    
    sidebarPanel(
      
      selectInput(
        inputId ="var1",
        label = "Select a Numerical Variable",
        choices = variables_names, selected = "Age"
      ),
      
      selectInput(
        inputId ="var2",
        label = "Select a Categorical Variable",
        choices = variables_names,
        selected = "Sex"
      ),
      
      radioButtons(inputId = "plot_choice", 
                   label = h3("Select Plot:"),
                   choices = c("Density Plot" = "density",
                     "Box Plot" = "box"),
                   selected = 'line'),
      
      sliderInput(inputId = "Age",
                  "Select Age Range:",
                  min = min(d$Age, na.rm=TRUE),
                  max = max(d$Age, na.rm=TRUE),
                  value= c(0, 80)),
      
      checkboxGroupInput(inputId = "survived", label = "Select if survived (0=no,1=yes)",
                         choices = names(table(d$Survived)), inline = TRUE)

    ),

    mainPanel(
      plotOutput(outputId = 'show_plot')
    )
  )
)

 
server <- function(input, output) {
  
  output$show_plot <- renderPlot({
    
    v1 = input$var1
    v2 = input$var2
   
    d <- d %>% filter(Age>input$Age[1], Age<input$Age[2])
    d <- d %>% filter(Survived %in% input$survived)
    
    library(ggplot2)
    
    if(input$plot_choice == 'density')
      
    {
      ggplot(d, aes(x = d[[v1]], color = as.factor((d[[v2]])))+
        geom_density()+
        labs(x = v1, color = v2))
    }
    
    else
    {
      ggplot(d, aes(x = d[[v1]], y = d[[v2]]))+
        geom_boxplot()+
        labs(x = v1, y = v2)
    }
  })
}
# app
shinyApp(ui = ui, server = server)
```

