---
title: "app9"
author: "Emma Schwartz"
date: "11/23/2020"
output: html_document
runtime: shiny
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(shiny)

d = read_csv("https://covidtracking.com/data/download/all-states-history.csv")
d <- d %>% filter(state=='CA'|state=='FL'|state=='TX'|state=='MA'|state=='NY'|state=='OH')


variables_names = names(d)

ui <- fluidPage(
  
  titlePanel("Covid 19 by States"),
  
  sidebarLayout(
    
    sidebarPanel(
      
      checkboxGroupInput(inputId = "state", label = "Select state to compare",
                         choices = names(table(d$state)), inline = TRUE),

      selectInput(
        inputId ="var1",
        label = "Select a Numeric Variable",
        choices = variables_names, selected = "positive"),
      
      sliderInput(inputId = "date",
                  "Select Date Range:",
                  min = min(d$date, na.rm=TRUE),
                  max = max(d$date, na.rm=TRUE),
                  value = c(as.Date("2020-1-22"), as.Date("2020-11-22"))),
      
      radioButtons(inputId = "plot_choice", 
                   label = h3("Select Plot:"),
                   choices = c("Line Plot" = "line",
                     "Point Plot" = "point"),
                   selected = 'line')
      
    ),

    mainPanel(
      plotOutput(outputId = 'show_plot')
    )
  )
)

 
server <- function(input, output) {
  
  output$show_plot <- renderPlot({
    
    v1 = input$var1
   
    d <- d %>% filter(state %in% input$state, date>input$date[1], date<input$date[2])
    
    library(ggplot2)
    
    if(input$plot_choice == 'point')
      
    {
      ggplot(d, aes(x = d$date, y = d[[v1]]))+
        geom_point()+
        labs(x = "date", y = v1)
    }
    
    else
    {
      ggplot(d, aes(x = d$date, y = d[[v1]]))+
        geom_line()+
        labs(x = "date", y = v1)
    }
  })
}
# app
shinyApp(ui = ui, server = server)
```

